# dev containers
quarkus.devservices.enabled=false
# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER_NAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
# flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
# logging
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %p <request-id:%X{req.id}> [%c] (%t) %s%n